[versions]
agp = "8.13.0"
coil = "2.7.0"
retrofit = "2.9.0"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"   # KSP版本（与Kotlin 2.2.0匹配）
coreKtx = "1.15.0"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"

espressoCore = "3.5.1"
constraintlayout = "2.2.1"
lifecycle = "2.9.4"
navigation = "2.9.5"
preferenceKtx = "1.2.1"
roomVersion = "2.6.1"
utilcodex = "1.31.1"
workerVersion = "2.9.1"

hiltVersion = "2.57.2"
hiltViewModel = "1.3.0"# androidx.hilt版本

paging = "3.3.6"

dslTablayout = "3.7.2"
shapeview = "9.2"
crashview = "2.4.0"
xpopup = "2.10.0"
liveEventBusX = "1.8.0"
retrofitLogging = "4.9.3"

[libraries]

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }

viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

paging = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
worker = { module = "androidx.work:work-runtime-ktx", version.ref = "workerVersion" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }

room-ktx = { group = "androidx.room", name = "room-ktx",version.ref = "roomVersion" }
room-runtime = { group = "androidx.room", name = "room-runtime",version.ref = "roomVersion" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "roomVersion" }
room-compiler = { group = "androidx.room", name = "room-compiler",version.ref = "roomVersion" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltVersion" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "retrofitLogging" }

# androidx.hilt 1.3.0 核心依赖
hilt-lifecycle-viewmodel = { group = "androidx.hilt", name = "hilt-lifecycle-viewmodel", version.ref = "hiltViewModel" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltViewModel" } # 可选：WorkManager注入
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltViewModel" } # 可选：Compose导航
hilt-compiler-androidx = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltViewModel" } # 注解处理器

dslTablayout = { group = "com.github.angcyo.DslTablayout", name = "TabLayout", version.ref = "dslTablayout" }
dslTablayout-vp1 = { group = "com.github.angcyo.DslTablayout", name = "ViewPager1Delegate", version.ref = "dslTablayout" }
dslTablayout-vp2 = { group = "com.github.angcyo.DslTablayout", name = "ViewPager2Delegate", version.ref = "dslTablayout" }

shapeview = { group = "com.github.getActivity", name = "ShapeView", version.ref = "shapeview" }
xpopup = { group = "com.github.li-xiaojun", name = "XPopup", version.ref = "xpopup" }
utilcodex = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
crashview = { module = "cat.ereza:customactivityoncrash", version.ref = "crashview" }
eventbus = { group = "io.github.jeremyliao", name = "live-event-bus-x", version.ref = "liveEventBusX" }

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }

[bundles]
# 依赖包（批量引入，可选）
#hilt = ["hilt-android", "hilt-android-compiler", "hilt-lifecycle-viewmodel", "hilt-compiler"]
#androidCore = ["core-ktx", "appcompat"]
navigation = ["navigation-fragment", "navigation-ui"]